agentAddress udp:161
sysLocation Docker SNMPv3 Lab
sysContact admin@example.local

createUser monitor SHA256 "auth-password" AES "priv-password"
rouser monitor authPriv

dontLogTCPWrappersConnects yes
