package mailconfig

import "testing"

func TestPasswordNodeCompatibleAndAuthenticated(t *testing.T) {
	// AES-GCM fixture generated by Node's crypto module with nonce=12 bytes of 0x01.
	config := Config{EncryptedPassword: "AQEBAQEBAQEBAQEBZxTUiYKgY83q4ZmzYsjG8It7iXPQIpMp8zfoyJg++w41OA=="}
	password, err := config.Password("test-only-secret")
	if err != nil || password != "test-only-password" {
		t.Fatalf("Node encrypted password did not round trip: %v", err)
	}
	if _, err := config.Password("wrong-secret"); err == nil {
		t.Fatal("wrong key was accepted")
	}
	config.EncryptedPassword = "short"
	if _, err := config.Password("test-only-secret"); err == nil {
		t.Fatal("invalid ciphertext was accepted")
	}
	if password, err := (Config{}).Password("test-only-secret"); err != nil || password != "" {
		t.Fatal("empty password should be supported")
	}
}
